sudo: false

env:

language: php

services:

php:
  - 7.0
  - 7.1
  - 7.2

before_install:

install:
  - travis_retry composer selfupdate
  - travis_retry composer install --no-interaction --prefer-source

before_script:

script:
  - composer fix --dry-run
  - composer test

after_success:
after_failure:
after_script:
before_deploy:
deploy:
after_deploy:
