sudo: false

env:

language: php

services:

php:
  - 7.1
  - 7.2

before_install:

install:
  - travis_retry composer selfupdate
  - travis_retry composer install --no-interaction --prefer-source

before_script:

script:
  - ./vendor/bin/php-cs-fixer --no-interaction
  - ./vendor/bin/phpunit --coverage-clover=coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

after_success:
after_failure:
after_script:
before_deploy:
deploy:
after_deploy:
